# Introdução ao problema

O mercado europeu de veículos usados movimenta bilhões de euros anualmente e apresenta forte competitividade, com variações significativas de preço influenciadas por múltiplos fatores técnicos e estruturais.

Neste projeto, realizo uma Análise Exploratória de Dados (EDA) em um conjunto de dados de veículos usados da União Europeia com o objetivo de identificar:

1. Principais fatores que impactam o preço;

2. Padrões de depreciação ao longo do tempo;

3. Diferenças de valor entre tipos de combustível e categorias;

4. Segmentações estratégicas de mercado.

O projeto envolve etapas completas de:

1. Limpeza e tratamento de dados;

2. Tratamento de valores ausentes;

3. Padronização de tipos;

4. Criação de novas variáveis (feature engineering);

5. Análise estatística descritiva;

6. Geração de insights orientados a negócio.

A proposta vai além da visualização gráfica, buscando transformar dados brutos em insights estratégicos aplicáveis a decisões comerciais, precificação e modelagem preditiva.

Este estudo demonstra a aplicação prática de técnicas de análise de dados voltadas para problemas reais de mercado, reforçando competências em manipulação de dados, raciocínio estatístico e geração de valor a partir de informação estruturada.

# Leitura e limpeza

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/fullGas.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21850 entries, 0 to 21849
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  21850 non-null  object
 1   Model                 21703 non-null  object
 2   Body                  21849 non-null  object
 3   Mileage_km            21850 non-null  int64
 4   Price                 21850 non-null  int64
 5   Year                  20770 non-null  float64
 6   Country               20115 non-null  object
 7   Condition             21850 non-null  object
 8   Fuel_Type             21833 non-null  object
 9   Fuel_Consumption_l    7342 non-null   float64
 10  Drivetrain            17113 non-null  object
 11  Gearbox               21511 non-null  object
 12  Gears                 13665 non-null  float64
 13  Power_hp              21850 non-null  int64
 14  Engine_Size_cc        18898 non-null  float64
 15  Cylinders             16755 non-null  float64
 16  Seats                 20701 non-null  float64
 17  Doors                 21188 non-null  float64
 18  Color                 20290 non-null  object
 19  Upholstery            17865 non-null  object
 20  Full_Service_History  21850 non-null  bool
 21  Non_Smoker_Vehicle    21850 non-null  bool
 22  Previous_Owners       11487 non-null  float64
 23  Seller                21773 non-null  object
 24  Image_url             21850 non-null  object
dtypes: bool(2), float64(8), int64(3), object(12)
memory usage: 3.9+ MB

In [4]:
df.describe()

,Mileage_km,Price,Year,Fuel_Consumption_l,Gears,Power_hp,Engine_Size_cc,Cylinders,Seats,Doors,Previous_Owners
count,2.185000e+04,2.185000e+04,20770.000000,7342.000000,13665.000000,21850.000000,18898.000000,16755.000000,20701.000000,21188.000000,11487.000000
mean,7.557876e+04,7.023929e+04,2016.931680,7.139077,6.078229,256.401053,2523.282781,5.106655,4.545288,4.127383,1.392008
std,3.457736e+05,2.279201e+05,9.713831,3.854358,1.814901,199.926795,1706.031977,2.519382,1.120274,1.178848,0.826377
min,0.000000e+00,1.000000e+00,1949.000000,0.100000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
25%,1.378800e+04,1.356375e+04,2014.000000,4.900000,5.000000,122.000000,1368.000000,4.000000,4.000000,3.000000,1.000000
50%,5.198350e+04,2.399000e+04,2020.000000,5.800000,6.000000,177.000000,1968.000000,4.000000,5.000000,5.000000,1.000000
75%,1.025045e+05,4.393625e+04,2023.000000,7.600000,7.000000,333.000000,3456.000000,6.000000,5.000000,5.000000,2.000000
max,1.677722e+07,9.999999e+06,2026.000000,55.000000,27.000000,3399.000000,56654.000000,50.000000,44.000000,6.000000,11.000000

In [5]:
df.shape

(21850, 25)

In [6]:
df.columns

Index(['Make', 'Model', 'Body', 'Mileage_km', 'Price', 'Year', 'Country',
       'Condition', 'Fuel_Type', 'Fuel_Consumption_l', 'Drivetrain', 'Gearbox',
       'Gears', 'Power_hp', 'Engine_Size_cc', 'Cylinders', 'Seats', 'Doors',
       'Color', 'Upholstery', 'Full_Service_History', 'Non_Smoker_Vehicle',
       'Previous_Owners', 'Seller', 'Image_url'],
      dtype='object')

In [7]:
# Identificando duplicatas
df.duplicated().sum()

np.int64(0)

In [8]:
# Remoção de duplicatas
df.drop_duplicates(inplace=True)

In [9]:
# Remoção de colunas que não serão utilizadas
df.drop(columns=['Fuel_Consumption_l', 'Image_url'], inplace=True)

In [10]:
# Verificação das alterações
df

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Drivetrain,...,Engine_Size_cc,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,White,Full leather,False,False,NaN,Dealer
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21845,Lexus,NX 350h,Off-Road/Pick-up,2500,52990,2025.0,DE,Used,Electric/Gasoline,4WD,...,2487.0,4.0,4.0,5.0,Black,Full leather,False,False,1.0,Dealer
21846,Lexus,NX 300h,Off-Road/Pick-up,170773,24900,2021.0,ES,Used,Electric/Gasoline,NaN,...,2494.0,NaN,5.0,5.0,White,NaN,False,False,NaN,Dealer
21847,Lexus,GS 300,Sedan,234500,8090,2009.0,ES,Used,Gasoline,Rear Wheel Drive,...,2995.0,6.0,5.0,4.0,Blue,NaN,False,False,NaN,Dealer
21848,Lexus,UX 250h,Off-Road/Pick-up,88764,17999,2020.0,IT,Used,Electric/Gasoline,Front Wheel Drive,...,1987.0,NaN,5.0,5.0,Grey,alcantara,False,True,1.0,Dealer
21849,Lexus,CT 200h,Sedan,62252,18490,2020.0,IT,Used,Electric/Gasoline,Front Wheel Drive,...,1798.0,4.0,5.0,5.0,Blue,NaN,False,True,1.0,Dealer

In [11]:
# Identificando valores ausentes
df.isna().sum()

Make                        0
Model                     147
Body                        1
Mileage_km                  0
Price                       0
Year                     1080
Country                  1735
Condition                   0
Fuel_Type                  17
Drivetrain               4737
Gearbox                   339
Gears                    8185
Power_hp                    0
Engine_Size_cc           2952
Cylinders                5095
Seats                    1149
Doors                     662
Color                    1560
Upholstery               3985
Full_Service_History        0
Non_Smoker_Vehicle          0
Previous_Owners         10363
Seller                     77
dtype: int64

In [12]:
# Tratamento dos valores
df.fillna({'Model':'Not informed'}, inplace=True)
df.fillna({'Body': 'Not informed'}, inplace=True)
df.fillna({'Country': 'Not informed'}, inplace=True)
df.fillna({'Fuel_Type': 'Not informed'}, inplace=True)
df.fillna({'Drivetrain': 'Not informed'}, inplace=True)
df.fillna({'Gearbox': 'Not informed'}, inplace=True)
df.fillna({'Gears': df['Gears'].median()}, inplace=True)
df.fillna({'Engine_Size_cc': df['Engine_Size_cc'].median()}, inplace=True)
df.fillna({'Cylinders': df['Cylinders'].median()}, inplace=True)
df.fillna({'Seats': df['Seats'].median()}, inplace=True)
df.fillna({'Doors': df['Doors'].median()}, inplace=True)
df.fillna({'Color': 'Not informed'}, inplace=True)
df.fillna({'Upholstery': 'Not informed'}, inplace=True)
df.fillna({'Previous_Owners': df['Previous_Owners'].median()}, inplace=True)
df.fillna({'Seller': 'Not informed'}, inplace=True)
df.fillna({'Power_hp': df['Power_hp'].mean()}, inplace=True)
df.fillna({'Full_Service_History': 'Not informed'}, inplace=True)
df.fillna({'Non_Smoker_Vehicle': 'Not informed'}, inplace=True)

In [13]:
# Correção focada na coluna 'Year'

# Remoção de registros sem ano
df = df[df['Year'].notna()]

# Converter para inteiro
df['Year'].astype('Int64')

0        2020
1        2017
2        2015
3        2008
4        2021
         ...
21845    2025
21846    2021
21847    2009
21848    2020
21849    2020
Name: Year, Length: 20770, dtype: Int64

In [14]:
# Alteração de tipo das colunas float
df[['Gears','Cylinders','Seats','Doors','Previous_Owners']].astype('Int64')

       Gears  Cylinders  Seats  Doors  Previous_Owners
0          6          4      4      3                1
1          5          4      4      3                4
2          5          4      4      3                1
3          5          4      4      3                2
4          6          4      4      3                1
...      ...        ...    ...    ...              ...
21845      6          4      4      5                1
21846      6          4      5      5                1
21847      6          6      5      4                1
21848      6          4      5      5                1
21849      6          4      5      5                1

[20770 rows x 5 columns]

In [15]:
# Verificação das alterações
df

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Drivetrain,...,Engine_Size_cc,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,White,Full leather,False,False,1.0,Dealer
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21845,Lexus,NX 350h,Off-Road/Pick-up,2500,52990,2025.0,DE,Used,Electric/Gasoline,4WD,...,2487.0,4.0,4.0,5.0,Black,Full leather,False,False,1.0,Dealer
21846,Lexus,NX 300h,Off-Road/Pick-up,170773,24900,2021.0,ES,Used,Electric/Gasoline,Not informed,...,2494.0,4.0,5.0,5.0,White,Not informed,False,False,1.0,Dealer
21847,Lexus,GS 300,Sedan,234500,8090,2009.0,ES,Used,Gasoline,Rear Wheel Drive,...,2995.0,6.0,5.0,4.0,Blue,Not informed,False,False,1.0,Dealer
21848,Lexus,UX 250h,Off-Road/Pick-up,88764,17999,2020.0,IT,Used,Electric/Gasoline,Front Wheel Drive,...,1987.0,4.0,5.0,5.0,Grey,alcantara,False,True,1.0,Dealer
21849,Lexus,CT 200h,Sedan,62252,18490,2020.0,IT,Used,Electric/Gasoline,Front Wheel Drive,...,1798.0,4.0,5.0,5.0,Blue,Not informed,False,True,1.0,Dealer

In [16]:
# Identificação dos valores NaN
df.isna().sum()

Make                    0
Model                   0
Body                    0
Mileage_km              0
Price                   0
Year                    0
Country                 0
Condition               0
Fuel_Type               0
Drivetrain              0
Gearbox                 0
Gears                   0
Power_hp                0
Engine_Size_cc          0
Cylinders               0
Seats                   0
Doors                   0
Color                   0
Upholstery              0
Full_Service_History    0
Non_Smoker_Vehicle      0
Previous_Owners         0
Seller                  0
dtype: int64

In [17]:
# Verificação de valores Nulos
df.isnull().sum()

Make                    0
Model                   0
Body                    0
Mileage_km              0
Price                   0
Year                    0
Country                 0
Condition               0
Fuel_Type               0
Drivetrain              0
Gearbox                 0
Gears                   0
Power_hp                0
Engine_Size_cc          0
Cylinders               0
Seats                   0
Doors                   0
Color                   0
Upholstery              0
Full_Service_History    0
Non_Smoker_Vehicle      0
Previous_Owners         0
Seller                  0
dtype: int64

# Exportação do dataframe limpo

In [18]:
df.to_csv('Dados UE.csv')

# Análise Exploratória de Dados (EDA)

In [19]:
# Adição de uma nova coluna identificando a categoria dos carros pegando como base o preço
def categorizar(Preco):
  if Preco <= 10000:
    return 'Compact'
  elif Preco <= 40000:
    return 'Average/Hatchback'
  elif Preco <= 45000:
    return 'SUV'
  else:
    return 'Premium'

df['Category'] = df['Price'].apply(categorizar)

/tmp/ipykernel_157/4218498993.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = df['Price'].apply(categorizar)

In [20]:
# Verificar a alteração no dataframe
df

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Drivetrain,...,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Category
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,White,Full leather,False,False,1.0,Dealer,Average/Hatchback
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer,Average/Hatchback
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer,Average/Hatchback
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer,Compact
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer,Average/Hatchback
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21845,Lexus,NX 350h,Off-Road/Pick-up,2500,52990,2025.0,DE,Used,Electric/Gasoline,4WD,...,4.0,4.0,5.0,Black,Full leather,False,False,1.0,Dealer,Premium
21846,Lexus,NX 300h,Off-Road/Pick-up,170773,24900,2021.0,ES,Used,Electric/Gasoline,Not informed,...,4.0,5.0,5.0,White,Not informed,False,False,1.0,Dealer,Average/Hatchback
21847,Lexus,GS 300,Sedan,234500,8090,2009.0,ES,Used,Gasoline,Rear Wheel Drive,...,6.0,5.0,4.0,Blue,Not informed,False,False,1.0,Dealer,Compact
21848,Lexus,UX 250h,Off-Road/Pick-up,88764,17999,2020.0,IT,Used,Electric/Gasoline,Front Wheel Drive,...,4.0,5.0,5.0,Grey,alcantara,False,True,1.0,Dealer,Average/Hatchback
21849,Lexus,CT 200h,Sedan,62252,18490,2020.0,IT,Used,Electric/Gasoline,Front Wheel Drive,...,4.0,5.0,5.0,Blue,Not informed,False,True,1.0,Dealer,Average/Hatchback

Análise de Variáveis Isoladas

In [21]:
# Contagem de modelos de carros e suas respectivas montadoras
model_counts = df.groupby('Model')['Make'].value_counts()
model_counts.sort_values(ascending=False)

Model      Make
Ypsilon    Lancia         636
Formentor  CUPRA          418
RAM        Dodge          325
Urus       Lamborghini    298
595        Abarth         295
                         ...
Z4 M       BMW              1
545        BMW              1
C-Crosser  Citroen          1
123        BMW              1
100        Audi             1
Name: count, Length: 656, dtype: int64

In [22]:
# Informações gerais da coluna Year
df['Year'].describe()

count    20770.000000
mean      2016.931680
std          9.713831
min       1949.000000
25%       2014.000000
50%       2020.000000
75%       2023.000000
max       2026.000000
Name: Year, dtype: float64

In [23]:
# Avaliar a concentração de carros por Ano
df['Year'].value_counts().sort_index()

Year
1949.0       3
1950.0       1
1953.0       1
1954.0       7
1955.0       6
          ...
2022.0    1848
2023.0    1587
2024.0    1723
2025.0    2653
2026.0      12
Name: count, Length: 76, dtype: int64

In [24]:
# Avaliar as categorias de carros
carros_categoria = df['Category'].value_counts().sort_values(ascending=False)
carros_categoria

Category
Average/Hatchback    11849
Premium               4827
Compact               3651
SUV                    443
Name: count, dtype: int64

In [25]:
# Análise da coluna Price
df['Price'].describe()

count    2.077000e+04
mean     6.695462e+04
std      2.205822e+05
min      1.000000e+00
25%      1.299000e+04
50%      2.348000e+04
75%      4.148750e+04
max      9.999999e+06
Name: Price, dtype: float64

In [26]:
# Identificação de Outliers da coluna Price

# 1° quantil
price_1quantil = df['Price'].quantile(0.25)

# 2° quantil
price_2quantil = df['Price'].quantile(0.50)

# 3° quantil
price_3quantil = df['Price'].quantile(0.75)

In [27]:
price_1quantil

np.float64(12990.0)

In [28]:
price_2quantil

np.float64(23480.0)

In [29]:
price_3quantil

np.float64(41487.5)

In [30]:
# Descriçã da coluna Body
df['Body'].describe()

count                20770
unique                  10
top       Off-Road/Pick-up
freq                  7863
Name: Body, dtype: object

In [31]:
# Frequência absoluta por carroceria
df['Body'].value_counts()

Body
Off-Road/Pick-up    7863
Sedan               4503
Coupe               2838
Compact             1875
Convertible         1375
Station wagon       1051
Van                  780
Other                454
Transporter           30
Not informed           1
Name: count, dtype: int64